#! /usr/bin/env bash

# This is the main file that runs the vortex command. It checks for the type of project passed as an positional argument and executes the correct function to setup the project from /vortex_project/lib/blueprints

# Get the directory where the script actually lives
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source helper functions/files
source "$SCRIPT_DIR/lib/guard"
source "$SCRIPT_DIR/lib/blueprints/node"
source "$SCRIPT_DIR/lib/blueprints/express"
source "$SCRIPT_DIR/lib/blueprints/cpp"
source "$SCRIPT_DIR/lib/blueprints/python"
source "$SCRIPT_DIR/lib/blueprints/web"
source "$SCRIPT_DIR/lib/github_setup"
source "$SCRIPT_DIR/lib/docker"

# Check system resources
check_system_resources

# Global Variables
PROJECT_NAME=""
PROJECT_TYPE=""

# Help manual
if [[ "$1" == "--help" || "$1" == "-h" ]]; then
    cat << EOF
Usage: vortex [-n | --name] [-t | --type] [-d | --docker] [-m | --monitor] [-h | --help]

A smart assistant to initialize development projects and monitor resources.

Options:
  -n, --name [NAME]    	Sets the project/folder name
  -t, --type [TYPE]    	Sets the environment (web, python, node, etc)
  -d, --docker         	Generates a Dockerfile
  -m, --monitor        	Checks RAM/Disk space before starting
  -h, --help   		Show this help manual

Examples:
  vortex -n my_web_app -t web -m
  vortex -h
EOF
    exit 0
fi

# Catch user input for the flags
while getopts ":n:t:dm" opt; do
    case "${opt}" in
    	n) PROJECT_NAME="$OPTARG" ;;
	t) PROJECT_TYPE="$OPTARG" ;;
 	d) create_docker_container=true ;;
 	m) run_monitor=true ;;
	\?)
	    echo "Error: Invalid option -$OPTARG." >&2
	    exit 1
	    ;;
	:)
	    echo "Error: Option -$OPTARG requires an arguemnt." >&2
	    exit 1
	    ;;
	*)
	    echo "Please enter a valid flag option and its corresponding argument: -n [NAME] | -t [TYPE] | -d | -m"
	    exit 1
	    ;;
    esac
done

# Check that the user entered a project name
if [[ -z $(echo "$PROJECT_NAME" | xargs) || "$PROJECT_NAME" == -* ]]; then
    echo "Error: Must provide a project name. Use -n [NAME]." >&2
    exit 1
fi

# Check that the user entered a project type
if [[ -z $(echo "$PROJECT_TYPE" | xargs) || "$PROJECT_TYPE" == -* ]]; then
    echo "Error: Must provide a project type. Use -t [TYPE]." >&2
    exit 1
fi

# Check if the project doesn't exist already
if [[ ! -d "$PROJECT_NAME" ]]; then
    check_dependency "$PROJECT_TYPE"

    # Execute project setup function depending on the project type
    case "$PROJECT_TYPE" in
        node) setup_node "$PROJECT_NAME" ;;
        express|ex) setup_express "$PROJECT_NAME" ;;
        cpp) setup_cpp "$PROJECT_NAME" ;;
        py|python) setup_py "$PROJECT_NAME" ;;
        web) setup_web "$PROJECT_NAME" ;;
        *) 
            echo "Project type not supported."
	    echo "Please pick one of these options: node | express | cpp | py | web"
	    exit 1 
	    ;;
    esac	

    #check_and_set_github_identity
    #init_repo "$project_name"
fi

# If the user asked for the project stats (typed the -m flag), print their stats
if [[ "$run_monitor" == "true" ]]; then
    display_system_stats "$PROJECT_NAME"
fi

# If the user asked to create docker container (typed the -d flag), create docker container
if [[ "$create_docker_container" == "true" ]]; then
    create_docker_file "$PROJECT_NAME" "$PROJECT_TYPE"
    create_docker_compose
    create_docker_ignore
    echo "Docker environment generated successfully for $PROJECT_NAME!"
fi
