#!/usr/bin/env bash

# Function to setup a C++ project
setup_cpp(){
    project_name="$1"
    
    echo "Initializing C++ project..."

    mkdir -p "$project_name"/src \
	     "$project_name"/include \
	     "$project_name"/build \
	     "$project_name"/bin \
	     "$project_name"/tests

    # Check that the directories exist
    if [[ -d "$project_name"/src \
	    && -d "$project_name"/include \
	    && -d "$project_name"/build \
	    && -d "$project_name"/bin \
	    && -d "$project_name"/tests ]]; then
       
        echo "Project directories successfully created."
	echo "Creating project files..."

        touch "$project_name"/include/main.hpp \
	    "$project_name"/src/main.cpp \
	    "$project_name"/MakeFile \
	    "$project_name"/.gitignore \
	    "$project_name"/README.md

	# Check if the files exits
	if [[ -f "$project_name"/include/main.hpp \
		&& -f "$project_name"/src/main.cpp \
		&& -f "$project_name"/MakeFile \
		&& -f "$project_name"/.gitignore \
		&& -f "$project_name"/README.md ]]; then

    	    cat << EOF > "$project_name"/include/main.hpp
#ifndef MAIN_HPP
#define MAIN_HPP

// Your function declarations go here


#endif
EOF

    	    cat << EOF > "$project_name"/src/main.cpp
#include <iostream>
#include "../include/main.hpp"

int main() {
    return 0;
}
EOF

    	    cat << EOF > "$project_name"/MakeFile
CXX = g++
CXXFLAGS = -Wall -Iinclude
SRC = src/main.cpp
TARGET = bin/app

all:
	@mkdir -p bin
	\$(CXX) \$(CXXFLAGS) \$(SRC) -o \$(TARGET)

clean:
	rm -rf bin/*
EOF

    	    cat << EOF > "$project_name"/.gitignore
bin/
build/
*.o
.DS_Store
EOF

    	    echo "# "$project_name"" > "$project_name"/README.md
   	    echo "C++ project is ready!"
        else
	    echo "Error: Files were not created. Please check your storage." >&2
	    exit 1
	fi
    else
        echo "Error: Directories were not created. Please check your storage." >&2
	exit 1
    fi
}
