#!/usr/bin/env bash

# Function to setup Node.js project 
setup_node(){
    NAME="$1"

    echo "Initializing Node.js project..."

    mkdir -p "$NAME"/src \
    	     "$NAME"/tests \
	     "$NAME"/config

    # Check that the directories exist
    if [[ -d "$NAME"/src \
	    && -d "$NAME"/tests \
	    && -d "$NAME"/config ]]; then

        echo "Project directories successfully created."
	echo "Creating project files..."

	touch "$NAME"/src/app.js \
    	      "$NAME"/.env \
	      "$NAME"/README.md \
	      "$NAME"/package.json

        # Check that the files exist
    	if [[ -f "$NAME"/src/app.js \
		&& -f "$NAME"/.env \
	       	&& -f "$NAME"/README.md \
		&& -f "$NAME"/package.json ]]; then

	    cat << EOF > "$NAME"/src/app.js
console.log("$NAME Node.js Project is live!");

// Basic logic placeholder
const start = () => {
    console.log("System heartbeat detected...");
};

start();
EOF

            cat << EOF > "$NAME"/package.json
{
  "name": "$NAME",
  "version": "1.0.0",
  "description": "A professional Node.js project initialized by Vortex",
  "main": "src/app.js",
  "scripts": {
    "start": "node src/app.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "Nada Shawer",
  "license": "ISC",
  "dependencies": {}
}
EOF

            echo "# "$NAME"" > "$NAME"/README.md
	    echo "Node.js project is ready!"
        else
            echo "Error: Files were not created. Please check your storage." >&2
            exit 1
        fi

    else
        echo "Error: Directories were not created. Please check your storage." >&2
	exit 1
    fi
}
