#!/usr/bin/env bash

# Function to setup Node.js project 
setup_node(){
    project_name="$1"

    echo "Initializing Node.js project..."

    mkdir -p "$project_name"/src \
    	     "$project_name"/tests \
	     "$project_name"/config

    # Check that the directories exist
    if [[ -d "$project_name"/src \
	    && -d "$project_name"/tests \
	    && -d "$project_name"/config ]]; then

        echo "Project directories successfully created."
	echo "Creating project files..."

	touch "$project_name"/src/app.js \
    	      "$project_name"/.env \
	      "$project_name"/README.md \
	      "$project_name"/package.json

        # Check that the files exist
    	if [[ -f "$project_name"/src/app.js \
		&& -f "$project_name"/.env \
	       	&& -f "$project_name"/README.md \
		&& -f "$project_name"/package.json ]]; then

	    cat << EOF > "$project_name"/src/app.js
console.log("$project_name Node.js Project is live!");

// Basic logic placeholder
const start = () => {
    console.log("System heartbeat detected...");
};

start();
EOF

            cat << EOF > "$project_name"/package.json
{
  "name": "$project_name",
  "version": "1.0.0",
  "description": "A professional Node.js project initialized by Vortex",
  "main": "src/app.js",
  "scripts": {
    "start": "node src/app.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "Nada Shawer",
  "license": "ISC",
  "dependencies": {}
}
EOF

            echo "# "$project_name"" > "$project_name"/README.md
	    echo "Node.js project is ready!"
        else
            echo "Error: Files were not created. Please check your storage." >&2
            exit 1
        fi

    else
        echo "Error: Directories were not created. Please check your storage." >&2
	exit 1
    fi
}
