#!/usr/bin/env bash

# Function to setup Python project
setup_py(){
    project_name="$1"

    echo "Initializing Python project..."

    mkdir -p "$project_name"/src \
    	     "$project_name"/tests \
	     "$project_name"/.venv

    # Check that the directories exist
    if [[ -d "$project_name"/src \
	    && -d "$project_name"/tests \
	    && -d "$project_name"/.venv ]]; then

	    echo "Project directories successfully created."
	    echo "Creating project files..."

        touch "$project_name"/src/main.py \
    	    "$project_name"/requirements.txt \
	    "$project_name"/README.md \
	    "$project_name"/.gitignore \
	    "$project_name"/.python-version

	# Check that the files exist
	if [[ -f "$project_name"/src/main.py \
		&& -f "$project_name"/requirements.txt \
		&& -f "$project_name"/README.md \
		&& -f "$project_name"/.gitignore \
		&& -f "$project_name"/.python-version ]]; then

	    cat << EOF > "$project_name"/src/main.py
def main():
    pass

if __name__ == "__main__":
    main()
EOF

    	    echo "# "$project_name"" > "$project_name"/README.md
    	    echo "Python project is ready!"
        else
	    echo "Error: Files were not created. Please check your storage." >&2
	    exit 1
	fi
    else
	echo "Error: Directories were not created. Please check your storage." >&2
	exit 1
    fi
} 
