#!/usr/bin/env bash

# Function to setup web project (HTML/CSS/JS)
setup_web(){
    local project_name="$1"

    echo "Initializing web project..."

    mkdir -p "$project_name"/css \
    	     "$project_name"/js \
	     "$project_name"/assets

    # Check that the directories exist
    if [[ -d "$project_name"/css \
	    && -d "$project_name"/js \
	    && -d "$project_name"/assets ]]; then

	echo "Project directories successfully created."
	echo "Creating project files..."

        touch "$project_name"/index.html \
    	    "$project_name"/css/styles.css \
	    "$project_name"/js/app.js \
	    "$project_name"/README.md

	# Check that the files exist
	if [[ -f "$project_name"/index.html \
		&& -f "$project_name"/css/styles.css \
	 	&& -f "$project_name"/js/app.js \
		&& -f "$project_name"/README.md ]]; then

    	    cat << EOF > "$project_name"/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <h1>Welcome to your "$project_name" web Project!</h1>
    <script src="js/script.js"></script>
</body>
</html>
EOF

    	    echo "# "$project_name"" > "$project_name"/README.md
    	    echo "Web project is ready!"
        else
	    echo "Error: Files were not created. Please check your storage." >&2
	    exit 1
	fi

    else
	echo "Error: Directories were not created. Please check your storage." >&2
	exit 1
    fi
}
