#!/usr/bin/env bash

# Function to setup express.js project
setup_express(){
    NAME="$1"

    echo "Initializing express.js project..."

    mkdir -p "$NAME"/src/routes \
    	     "$NAME"/src/controllers \
	     "$NAME"/src/middleware \
	     "$NAME"/src/types \
	     "$NAME"/src/models \
	     "$NAME"/public/css \
	     "$NAME"/views

    # Check that the directories exist
    if [[ -d "$NAME"/src/routes \
	    && -d "$NAME"/src/controllers \
	    && -d "$NAME"/src/middleware \
	    && -d "$NAME"/src/types \
	    && -d "$NAME"/src/models \
	    && -d "$NAME"/public/css \
	    && -d "$NAME"/views ]]; then

        echo "Project directories successfully created."
	echo "Creating project files..."

    	touch "$NAME"/.env \
            "$NAME"/.gitignore \
	    "$NAME"/README.md \
	    "$NAME"/app.ts \
	    "$NAME"/package.json \
	    "$NAME"/tsconfig.json \
	    "$NAME"/views/index.ejs \
	    "$NAME"/public/css/styles.css

	# Check that the files exist
	if [[ -f "$NAME"/.env \
		&& -f "$NAME"/.gitignore \
		&& -f "$NAME"/README.md \
		&& -f "$NAME"/app.ts \
		&& -f "$NAME"/package.json \
		&& -f "$NAME"/tsconfig.json \
		&& -f "$NAME"/views/index.ejs \
		&& -f "$NAME"/public/css/styles.css ]]; then


    	    cat << EOF > "$NAME"/app.ts
import express, { Request, Response } from 'express';
import dotenv from 'dotenv';

dotenv.config();

const app = express();
const PORT = process.env.PORT || 3000;

app.get('/', (req: Request, res: Response) => {
    res.send('"$NAME" TypeScript Express Server is Live!');
});

app.listen(PORT, () => {
    console.log(\`[server]: Server is running at http://localhost:\${PORT}\`);
});
EOF

	    cat << EOF > "$NAME"/package.json
{
  "name": "$NAME",
  "version": "1.0.0",
  "main": "dist/index.js",
  "scripts": {
    "build": "tsc",
    "start": "node dist/app.js",
    "dev": "ts-node-dev --respawn app.ts"
  },
  "dependencies": {
    "express": "^4.18.2",
    "dotenv": "^16.0.3"
  },
  "devDependencies": {
    "@types/express": "^4.17.17",
    "@types/node": "^20.2.5",
    "typescript": "^5.0.4",
    "ts-node-dev": "^2.0.0"
  }
}
EOF

	    cat << EOF > "$NAME"/tsconfig.json
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true
  },
  "include": ["src/**/*"]
}
EOF

	    cat << EOF > "$NAME"/views/index.ejs
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
    <link rel="stylesheet" href="/public/styles.css">
</head>
<body>
    
</body>
</html>
EOF

            echo "# "$NAME"" > "$NAME"/README.md
            echo "Express.js project is ready!"
        else
	    echo "Error: Files were not created. Please check your storage." >&2
	    exit 1
	fi
    else
        echo "Error: Directories were not created. Please check your storage." >&2
	exit 1
    fi
}
