#!/usr/bin/env bash

# cd into the project directory because we need to be inside a git repo
cd $HOME/vortex_project || { echo "Error: Could not find project directory"; exit 1; }

# File with the channel webhook for where to send the notification
CONFIG_FILE="$HOME/.vortex_config"

# Check the config file exists, if not create it
if [[ -f "$CONFIG_FILE" ]]; then
    source "$CONFIG_FILE"
else
    echo "Discord webhook not configured in $CONFIG_FILE"
    read -p "Please enter your Discord webhook URL: " user_d_webhook
    echo "VORTEX_D_WEBHOOK=\"$user_d_webhook\"" > "$CONFIG_FILE"
    VORTEX_D_WEBHOOK="$user_d_webhook"
fi

# Temp file to store the notified count so it's not lost after systemd ends
inserts_num_file="/tmp/vortex_ghost_state"

# Global variable that stores the last count where the user was given a notification in a file
last_notified_count=$(cat "$inserts_num_file" 2> /dev/null || echo 0)

# Get number of insertions and deletions in a git project directory
num_of_mods_in_dir(){
    # Get number of modifications in both tracked and untracked (new) files
    local tracked_stats=$(git diff HEAD --shortstat)
    local untracked_lines=$(git ls-files --others --exclude-standard | xargs -I {} wc -l {} | awk '{sum += $1} END {print sum}')
    local untracked_lines=${untracked_lines:-0}

    num_of_inserts=0
    num_of_deletes=0

    if [[ -n "$tracked_stats" ]]; then
	num_of_inserts=$(echo "$tracked_stats" | grep -oP '\d+(?= insertion(s)?)' || echo 0)
	num_of_deletes=$(echo "$tracked_stats" | grep -oP '\d+(?= deletion(s)?)' || echo 0)
    fi
    
    # Final cleanup to ensure they are numbers
    num_of_inserts=$((num_of_inserts + untracked_lines))
    num_of_deletes=$((num_of_deletes + 0))
}

num_of_mods_in_dir	# call the function

# Send notification msg to discord channel if the user made 50+ insertions
send_commit_ntf(){
    if [[ "$num_of_inserts" -ge 50 && "$num_of_inserts" -gt "$last_notified_count" ]]; then
        curl -X POST "$VORTEX_D_WEBHOOK" \
        -H "Content-Type: application/json" \
        -d "{\"content\": \"**VORTEX GHOST ALERT**\nInsertions: $num_of_inserts\nDeletions: $num_of_deletes\n\nMaybe it is a good time to commit now?\"}"

        echo "$num_of_inserts" > "$inserts_num_file"
    fi
}

send_commit_ntf		# call the function
