#!/usr/bin/env bash

# This is the script that checks the user has sufficient memory, system resources, and the required dependencies to actually create their project. It also generates a specific system/project stats report if they run the -m flag.

# Check there is enough disk space and memory (silent check before the vortex command runs anything else)
check_system_resources(){
    local available_disk_space=$(df -BG / --output=avail | tail -1 | sed 's/G//' | xargs)
    local available_ram=$(free -m | awk '/^Mem:/ {print $NF}')

    if (( $(echo "$available_disk_space < 1" | bc -l) )); then
        echo "Error: Insufficient disk space."
	exit 1
    fi

    if [[ "$available_ram" -lt 256 ]]; then
        echo "Error: Insufficient memory space."
	exit 1
    fi

    echo "System resources check passed!"
}

# Print system resources stats to user when they type the -m flag
display_system_stats(){
    local dir_name="$1"
    
    # Get disk/system stats
    local ds_size=$(df -BG / --output=size | tail -1 | sed 's/G//' | xargs)
    local ds_used=$(df -BG / --output=used | tail -1 | sed 's/G//' | xargs)
    local ds_avail=$(df -BG / --output=avail | tail -1 | sed 's/G//' | xargs)
    local ds_use_percent=$(df -BG / --output=pcent | tail -1 | sed 's/G//' | xargs)
    local m_total=$(free -m | awk '/^Mem:/ {print $2}')
    local m_used=$(free -m | awk '/^Mem:/ {print $3}')
    local m_free=$(free -m | awk '/^Mem:/ {print $NF}')

    # Get specific project stats
    local dir_size=$(du -sh "$dir_name" | awk '{print $1}')
    local file_count=$(find "$dir_name" -type f | wc -l)
    local dir_count=$(find "$dir_name" -type d | wc -l)


    # Print stats as a report
    echo -e "\n\e[1;34mVORTEX SYSTEM REPORT\e[0m"
    echo "=========================================="
    echo -e "\n\e[1;34mSYSTEM STATS\e[0m"
    (
    echo "Resource Total Used Avail/Free Usage%"
    echo "Disk ${ds_size}G ${ds_used}G ${ds_avail}G ${ds_use_percent}"
    echo "RAM ${m_total}M ${m_used}M ${m_free}M ---"
    ) | column -t
    echo "------------------------------------------"
    echo -e "\n\e[1;34m$dir_name PROJECT STATS\e[0m"
    (
    echo "Size ${dir_size}"
    echo "Files ${file_count}"
    echo "Folders ${dir_count}"
    ) | column -t
    echo "=========================================="
}

# Hints for missing dependencies
give_hint(){
    case "$1" in
        node|npm) echo "Hint: Try 'sudo apt install nodejs npm'" >&2 ;;
	g++|make) echo "Hint: Try 'sudo apt install build-essential'" >&2 ;;
	python3|pip3) echo "Hint: Try 'sudo apt install python3-pip'" >&2 ;;
    esac
}

# Check dependencies are installed
check_dependency(){
    local tool=""
    local project_type=$1
    echo "Checking the dependencies for $project_type project..."

    case "$project_type" in
        node)
	    for tool in node npm; do
	        if ! command -v "$tool" &> /dev/null; then
                    echo "Error: $tool not installed." >&2
		    give_hint "$tool"
		    exit 1
	        fi
	    done
	    ;;
	express)
	    for tool in node npm; do
                if ! command -v "$tool" &> /dev/null; then
                    echo "Error: $tool not installed." >&2
                    give_hint "$tool"
		    exit 1
                fi
            done
            ;;             
	cpp)
	     for tool in g++ make; do
                if ! command -v "$tool" &> /dev/null; then
                    echo "Error: $tool not installed." >&2
                    give_hint "$tool"
		    exit 1
                fi
            done
            ;;
	py)
	    for tool in python3 pip3; do
                if ! command -v "$tool" &> /dev/null; then
                    echo "Error: $tool not installed." >&2
                    give_hint "$tool"
		    exit 1
                fi
            done
            ;;
	web)
	    echo ""
	    ;;
	*)
	    echo "Please enter a valid project type." >&2
	    exit 1
	    ;;
    esac
}
